---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USERNAME: cm9vdA== # base64 of "root"
  DB_PASSWORD: cGFzc3dvcmQ= # base64 of "password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-svc:3306/ayogyafirst?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update" #
  SPRING_JPA_SHOW_SQL: "false" #
